### ISSUE TITLE
Release of Dockerfile from domistyle/emby

### ISSUE THREAD

**Issue by RaymondSchnyder** [DomiStyle/emby-issues#1]
Hello Domistyle,

I saw your image on dockerhub "domistyle/emby".
And wanted to fork it, to add some features.
But the dockerfile for it is not available.
I tried to reverse engineer the Dockerfile, but its really a pain in the ass.
So i wanted to ask if you could release the Dockerfile / the Source code of the image.

Thank you and have a nice day

**Comment by DomiStyle** [comment]
@RaymondSchnyder Sure, you can find the Dockerfile [here](https://git.dhome.at/DomiStyle/emby/blob/master/Dockerfile).

**Comment by RaymondSchnyder** [comment]
@DomiStyle I love you, thank you very very much!
